export const secretkeyActionTypes = {
    SECRET_KEY_USER_DATA : "SECRET_KEY_USER_DATA",
    DELETE_SECRET_KEY_USER_DATA : "DELETE_SECRET_KEY_USER_DATA",
    UPDATE_SECRET_KEY_USER_DATA: "UPDATE_SECRET_KEY_USER_DATA",
    USER_IMAGE_DATA:"USER_IMAGE_DATA",
    CLEAR_IMAGE_DATA:"CLEAR_IMAGE_DATA"
}